notifications:
  email: false
sudo: true
language: python
matrix:
  fast_finish: true
cache:
  - pip
python:
  - '2.7'
  - '3.5'

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats tree git
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install -r requirements-test.txt
  - pip freeze

install:
  - travis_retry pip install -e .

script:
  - ./run_tests.sh

after_success:
  - coveralls

deploy:
  provider: pypi
  user: dcaro
  distribution: sdist
  password:
    secure: "YTItDY6A3w2cTqORJZsnqum42X9axvw6Do/k36sGozrP/ANdwgsluoRHkuXgqnVkmFI42/hh4/mu66vZudscXdg8JDtPYMaDPiDdKSv6jEdHxXFGLczyYCM9Zu3Z4xgpkF3AFrXhoSAXOBEy5MzOLD5DugvwZSHoifxGfThyTiFf+wT70sx0EkK896s2dnw5we92lnjC+OcyMXxig43FC0rT/2BupxmVBwyCm+LMJEK9YtNc2D3Ij+rSBq2EqyZMXJgyCL/1uIqmSIrpxpW/z4cjcdRK/FTGag3ZFneUcPV+/MLdMS45gk5Nc2qkmGF8g+HgA9v06xLudLybW3CQ2esugyfsW5xsTZc6mylr1lqR4WmX7mLsi5n8fQIYtFsezhl+yx4O0Fy2hF6gmMWsaA7gSJ/8Cu2JrM1yvxNodlUqySdODFfmWLWrPeeW9IPsfgf0eVHIoCmQL3wHnEiGJRGQwTQaXOHNYbLtz9Q8Td2NOIS1QkaqL9bYCuj7JyEU/Z+oKLyY/BOWB0CxttMXQ0VBzBqkZo0/ldPDAUDClQFDgjU9aO22cRNLtyIy5xGxRHqd9oahN5k0lyODjxrDrARngCmg3Sxw7UpWG+Fc9uuH3tPUMOW2mkHZlJbXBiT48YFeLo/wyo3hALuMBLWuxGgDxi85jIsKWEc1cMzIrKE="
  on:
    branch: master
    python: '2.7'
