name: Main tests

on:
  push:
  pull_request:

jobs:
  black:
    name: Check formatting with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install -r requirements-test.txt
          black --check --diff .

  isort:
    name: Check imports with isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install -r requirements-test.txt
          isort --check-only --diff .

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-test.txt
          pip install -e .
      - name: Run tests
        run: pytest --cov=autosemver --cov-report=term-missing -vv tests/unit autosemver

# TODO
#  mypy:
#    name: Run type checks
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#      - run: |
#          pip install -r requirements-test.txt
#          mypy . --ignore-missings-imports
